### ISSUE TITLE
Meta: :calendar: Events

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#103]
This issues is a meta issue for all Events issues:

**Feature Completion:**
* [x] #29 Events overview list
* [x] #30 Create, edit, delete, publish events
* [x] #247 Link POIs to events in event form
* [x] #245 Add filter in event list
* [x] #251 Add TinyMCE to event form

**Additional Features:**
* [x] #100 Subscribe/import iCal calendar (Additional Features)
* ~~#101 Subscribe/import CalDAV calendar (Additional Features)~~
* [ ] #102 Export events as iCal (Additional Features)
* [x] #246 Client side validation in event form (Additional Features)

**Comment by osmers** [comment]
Closing this as completed - any issues related to events will have the lable topic:events
