### ISSUE TITLE
Meta-description for root-level pages

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-cms#2563]
### Motivation

To improve SEO and show pretty search results, we want to have a translatable meta-description of the integreat "root"/"landing" page. 

### Proposed Solution

- [ ] In the "Netzwerkverwaltung" add a new section for SEO. 
- [ ] There you can set the title for the page of the root page.
- [ ] There you can set meta-description for the root page.

Relates to #522, #402

**Comment by laravoelk** [comment]
@MizukiTemma I have one question concerning this topic: Is it planned that municipalities add the title and meta description for the root page or would it be generated automatically?

**Comment by MizukiTemma** [comment]
> [@MizukiTemma](https://github.com/MizukiTemma) I have one question concerning this topic: Is it planned that municipalities add the title and meta description for the root page or would it be generated automatically?

@laravoelk 
We imagined following things:
- A new field appears for meta-description
- Someone has to create a German (root-language) version manually
- Translations can be created either per MT or by translators

**Comment by MizukiTemma** [comment]
It seems the topic needs some more context and clarifying (at least for me 😅):

- Which page exactly is _the integreat "root"/"landing" page_? Will there be one single meta-description for all Integreat regions or one meta-description for each region?
- If it is about a meta-description per region: who creates and update it? Service Team or users of the regions? Anyway, more effort for update/managing. (to the question "_we want to make it sure that this new feature is "good" for region users._")

@laravoelk @hauf-toni @digitalfabrik/app-team

**Comment by laravoelk** [comment]
Same for me ;-) I would also like to know the Integreat root / landing page. 
I am not sure if just one meta descirption for all regions will be so helpful as the desciption would be very general.

**Comment by steffenkleinle** [comment]
TBH: No clue anymore why and for what we need this. I guess it would be nice in theory that every city can provide a customized meta description, but it might be a pain to maintain in reality. Also, since nobody ever asked about this/we did not get any complaints we might also just close this from my perspective.
