### ISSUE TITLE
Meta-description for pages/events/pois

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#522]
### Motivation

To improve SEO, we want to add the possibility to add meta-descriptions for pages/events/pois.

### Proposed Solution

- [ ] Add a new field `meta_description = models.TextField(blank=True)` to `AbstractBasePageTranslation`, `EventTranslation` and `POITranslation` models.
- [ ] Add this field to the `PageTranslationForm`, `EventTranslationForm` and `POITranslationForm`.
- [ ] Add a new textarea beneath the `text`/`description` fields to the templates of that form (`page_form.html`, `event_form.html`, `poi_form.html`).
- [ ] Add `description` property to the `Region` model, which can be used for the content overview in the app.

**Comment by svenseeberg** [comment]
The challenge here is that our content creators do not know anything about SEO. Therefore we need to steer them into a direction that in the end results in a good meta information. We could have an additional input field that asks for a 1 to 3 sentences summary of the page content.

**Comment by JoeyStk** [comment]
@steffenkleinle could you please give an update if this is still wanted and if so, why :)

**Comment by steffenkleinle** [comment]
I think this is not really my place to tell. This is more a question for the PO/the service team whether they deem it necessary/sensible that cities can edit the meta description to improve on the SEO.

**Comment by hauf-toni** [comment]
waiting for input from the service team’s perspective — I'll get back to you asap @JoeyStk

**Comment by laravoelk** [comment]
We will talk about this at the conference with the whole team and get back to you next week. :-)

**Comment by steffenkleinle** [comment]
> We will talk about this at the conference with the whole team and get back to you next week. :-)

Perhaps this should even be an even bigger discussion including the marketing team as this is mainly relevant for SEO.

**Comment by laravoelk** [comment]
We have discusses this issue at the conference and we were wondering if it would generally be possible to include AI, so that the Meta description is automatically generated and municipalities can just change it if they need.
