### ISSUE TITLE
Polish Dashboard for a better overview

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#687]
### Motivation
So far, the dashboard consists of multiple different aspects. This should be streamlined in one consistent state.

We should also reduce dashboard data to actionable information.

### Proposed Solution

- [x] The RSS feed should be reduced to show only 3 entries and has the possibility to async load more.
- [x] Rename "Tür an Tür - Digitalfabrik News" to "Integreat News"
- [x] The "At a glance" section should consist of a short overview of the current hits (see #1 )
- [x] A overview of the translation report (see #502 )
- [x] An overview of the results of the broken link (#81 )
- [ ] Outdated pages ( #1939 )
- [ ] App size ( #78 )
- [ ] List pages with bad HIX index ( #2088 )

**Comment by svenseeberg** [comment]
@ulliholtgrave the last linked issue is closed. AFAICT this ticket is also "done"?! I'll close it, please reopen if this is wrong.

**Comment by ulliholtgrave** [comment]
@svenseeberg Yes, it's closed, but so far we have no widget element for the translation reports. Therefore, I would leave it open, but remove it from the Version 1.0 milestone. I am aiming for some adjustments on the dashboard, as it's current state is okayish, but could be improved

**Comment by ulliholtgrave** [comment]
The following things could be improved:

- Highlight actionable information (i.e. Outdated translations, broken links etc.)
- Move less important information to bottom of screen(?)
- Filter RSS-Feed by categories and only show relevant news items

**Comment by ulliholtgrave** [comment]
Possible layout: https://themes-backend.material-ui.com/wp-content/uploads/2019/08/tabler-react.com_-min-e1565617941333.png

**Comment by ulliholtgrave** [comment]
![Dashboard CMS_Draft](https://user-images.githubusercontent.com/15608678/152195203-709b50a6-b718-4138-a682-6f34f6d34efb.png)
This is the design that should be implemented for the dashboard.

**Comment by svenseeberg** [comment]
@ulliholtgrave I think this issue is more and more redundant to #133. I think we should just close it.

**Comment by ulliholtgrave** [comment]
@svenseeberg Referring to your comment in #133 I guess you are right :+1:
